### ISSUE TITLE
Overview & checklist

### ISSUE THREAD

**Issue by Jeeyool** [Jeeyool/CPR-FINAL#1]
- create
    - [ ]  testing is not provided
    - [ ]  main
- team leader submits one(the final product) on BlackBoard
- Due date: December 9th
- no live meeting next week, but if you have a question, you can come ask

---

**Note**

- Students will ***enter*** their module's C code, ***comment it***, ***compile it, create unit** **test cases, run,*** and ***capture the results of tests.***
- ***4 calendar days after the Project Management class,** 
any group member not communicating will be removed from the group*
- Your group will complete a coding project in the latter stages of the **SDLC**
- **2 calendar days after PM class,**
*Submit activity ideas to* group members even if activity was not submitted for marking
- ***Always* collaborate using your group's MS Teams channel**
- ***6 calendar days after PM class**
Group members share their module's commenting and test cases with other group members. +
Group members meet and establish standards of work quality and quantity.*

## **Start**

- Overview
    - [x]  See the Final Project Overview
    - [x]  See the tutorial
        - [Link](https://www.youtube.com/watch?v=WK6y6F2_7VI)
- Set up development tools for the project:
    - [ ]  See **Minimalist GNU** for Windows to get the GCC compiler
        - if we have already installed Visual Studio, do we still need to install it?
    - [ ]  See How to Install git ( for Version2+ )
        - [Video](https://youtu.be/tudlTazZh28)
        - [git basics.docx](https://learn.senecacollege.ca/bbcswebdav/pid-11777176-dt-content-rid-57347068_3/xid-57347068_3)
- Create a joint Assignment Plan spreadsheet
    - [ ]  **Use the Plan.xlsx f**or project coordination and individual work items
    - [ ]  Describe each group member's individual responsibilities
    - Everyone should outline ideas and approaches for **all** aspects of the project, then share those outlines with each other.
    - Update the Assignment Plan/Tasks as work progresses to indicate steps completed and new steps added as needed.
    - stored in your Team / Channel Files
- **Team Meeting**
    - Role Assignment: leader, 1-3
    - Time planning
        - Each deadline
        - Feedback
        - Regular Team meeting if necessary
    

### **Version 1**

- [ ]  code (copy the content)
    - See **png files**
    - Use your favorite editor; create/open a folder for the final project
        - You can compile, debug, and test normally, but will have to do some file management or enter some long paths to add the IDE project's .c files with the git repository in Version 2.
- [ ]  comment
    - See **Programming Comments.doc**
- [ ]  test
    - [ ]  Develop Test cases to test all lines of code
        - See Programming Test Cases.docx and test case template.xlsx
        - Create your own test data which never uses repetition
- [ ]  compile
    - Must use the command line gcc to compile all files
- [ ]  Run and document the test case results
    - [ ]  Capture the console output of your tests and paste it into a test case file
- [ ]  send it to a team leader

**Team leader**

- [ ]  compile 4 modules
- [ ]  combine
- [ ]  thorough testing
- [ ]  Select all, copy them, paste in notepad++, screenshot
- Lists of files to be submitted (Version 1)
    1. fundamentals
        1. h – code entered, commented.
        2. c – Version 1 code entered, commented, compiled.
        3. xlsx – comprehensive unit tests to be run, with a record of post-test results.
        4. txt – console text captured showing unit test inputs and outputs.
        5. forward a, b, c, and d files to team leader
    2. manipulating
        1. per 1. above
    3. converting
        1. per 1. above
    4. tokenizing
        1. per 1. above
    5. c
        1. c – code entered, commented, compiled.
        2. xlsx – simple integration tests to be run, with a record of post-test results.
        3. txt – console text captured showing integration test inputs and outputs.
    6. xlsx – updated with actual hours and all tasks' status at time of submission.
    7. Team leader assembles all module files from 1 – 4, along with project level files 5 & 6, into a zip archive and submits to Blackboard.
        1. Do NOT include .exe or image files.

---

### **Version 2**

- [ ]  Set up git
    - [ ]  download git
        - [git link](http://git-scm.com/)
    - [ ]  Video tutorial
        - [How to install git](https://www.youtube.com/watch?v=tudlTazZh28&feature=youtu.be)
        - [How to use git (37 min.)](https://www.youtube.com/watch?v=I1SOAcJJ6TE)
- [ ]  initialize and configure git repository, go through process of adding version 1 code to the repo and commit.
- [ ]  See **Final Project Overview** and add the Ver.2 functionality
    - enter _v2 C code found in the Project Source Code.zip
- [ ]  comment
- [ ]  compile
- [ ]  develop and run test cases
- [ ]  capture results and paste it into test case
- [ ]  use git to promote Ver.2
- Lists of files to be submitted (Version 2)
    
    It includes the same files as for Version 1 with Version 2 requirements added to those same files, plus files unique to Version 2.
    
    1. fundamentals – Version 2 tasks and the additional submission file  **txt**
        1. git init, config. See "git basics.docx"
        2. git add & commit source code files from Version 1
            1. $ git status # should *not* show "Changes to be committed:"
            2. $ git log # should show a commit, e.g.  commit 3f936d4ce955d7237eebd6e88887dbd6c719bc10 Author: You <yourID@mySeneca.ca> Date: Mon Apr 12 13:01:44 2021 -0400 *version1-commit-message*
    - $ git log -p > "fundamentals_git_log.txt" # check contents for Version 1 details
    1. c – Version 2 code added to Version 1 source file, commented, compiled.
    2. xlsx – comprehensive unit tests to be run for Version 2 code added to Version 1 tests, with a record of post-test results.
    3. txt – console text captured showing unit test inputs and outputs.
        1. **It is necessary to repeat the previous version's tests in addition to the new version's test.  Assuming new code added will not affect the existing code is a bad assumption  – that is a frequent cause of bugs in the (less than) professional programming world.**
    4. git add & commit source code files from Version 2
        1. see above as in b. / i. and ii.
    5. git log -p > "fundamentals_git_log.txt" # check for Versions 1 & 2 details
    6. forward h, ___.c, **____git_log.txt**, ____test_cases.xlsx, ____testing.txt files to team leader
    7. manipulating
        1. per above
    8. converting
        1. per above
    9. tokenizing
        1. per above
    10. c
        1. c – code entered, commented, compiled.
        2. xlsx – simple integration tests to be run, with a record of post-test results.
        3. txt – console text captured showing integration test inputs and outputs.
    11. xlsx – as per above including both Version 1 and Version 2 project plans.
    12. Team leader duties – as per above.
- **1 calendar day after IP class**
*All group members have contributed to Version 1 according to their group's established standard quality of work.*
    - Please check your quality against the P**rogramming Comments.docx** and **Programming Test Cases.docx requirements.**
    - [ ]  Group requests a qualitative project review @instructor byproviding a link to the folder containing all project files.
    - [ ]  A group member requests review of an individual file byopening it, clicking "Conversation" for Office files or the round speech bubble in upper right, then @instructor asking for review.
    - [ ]  Group adjusts Version 1 after feedback. Optionally goes on to add Version 2.
- **+2 - 4 calendar days after IP class**

---

### **Version 3**

- [ ]  See **Final Project Overview** and add the Ver.3 functionality
    - [Video tutorial](https://www.youtube.com/watch?v=B12Ci7bHIEY&feature=youtu.be) (31 min.)
    - enter _v3 C code found in the Project Source Code.zip.
- [ ]  comment
- [ ]  compile
- [ ]  develop and run test cases
- [ ]  capture results and paste it into test case
- [ ]  use git to promote Ver.3
- Lists of files to be submitted (Version 3)
    1. Fundamentals – Version 3 tasks
        1. c – Version 3 code added to Version 2 source file, commented, compiled.
        2. xlsx – comprehensive unit tests to be run for Version 3 code added to Version 2 tests, with a record of post-test results.
        3. txt – console text captured showing unit test inputs and outputs.
        4. git add & commit source code files from Version 3
            1. $ git status # should *not* show "Changes to be committed:"
            2. $ git log # should show a commit, e.g.  commit 3f936d4ce955d7237eebd6e88887dbd6c719bc10 Author: You <yourID@mySeneca.ca> Date: Mon Apr 12 13:01:44 2021 -0400 *version3-commit-message*
    - $ git log -p > "fundamentals_git_log.txt" # check for Versions 1 & 2 & 3 details
    1. manipulating
        1. per 1. above
    2. converting
        1. per 1. above
    3. tokenizing
        1. per 1. above
    4. c
        1. c – code entered, commented, compiled.
        2. xlsx – simple integration tests to be run, with a record of post-test results.
        3. txt – console text captured showing integration test inputs and outputs.
    5. xlsx – as per above including Version 1, 2, and 3 project plans.
    6. Team leader duties – as per above.
- [ ]  Update Assignment Plan with actual accomplishments by each team member
    - The Assignment Plan and submission comments must declare differences among members' contributions to the project's versions.
- **by +6 calendar days after IP class**
    - [ ]  Requests @instructor for qualitative review will receive feedback in order received and in reverse order of versions: 3, 2, 1.
- **Before Last Class of the Term**
    - [ ]  Requests @instructor for qualitative review will receive feedback in order received and in reverse order of versions: 3, 2, 1
- **Last Class of the Term**
    - Deadline for instructor review requests is start of last class;
    - feedback is on best efforts basis until end of class.
    - Final Project submission due by midnight EDT;
    - one submission with a minimum of Version 1.
- Submission
    - **One group member submits the Project.zip to Bb for grading on behalf of the team.**
    - Using **Add Comments,** include a link to your MS Team Channel's File tab and the name (Bb ##) of your MS Team Channel. **Note there whether all group members contributed equally and deserve the same marks, or how team member contributions varied.**
    -
